name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Java 8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8

    - name: Run Tests
      run: mvn test

    - name: Setup Java 11 # SonarCloud does not support Java 8 anymore!
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11

    - name: Dump Github Context
      env:
        SECRETS: ${{ toJson(secrets) }}
      run: |
        echo "$SECRETS"


    - name: Scan with SonarCloud
      run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
